# ---------------------------------------------------------
# File system cleanup - Record Powershell version
# Marcel Jussen
# 07-12-2015
# ---------------------------------------------------------
#requires -version 2.0
$Version = $PSVersionTable.PSVersion
"Powershell version $Version" | Out-File C:\Logboek\Cleanup\PSVersion.log
Write-Host "Powershell version $Version"
# ---------------------------------------------------------


# SIG # Begin signature block
# MIIHjwYJKoZIhvcNAQcCoIIHgDCCB3wCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUgV3ObWHyeqY65QX/5kaca6r5
# 9wCgggWFMIIFgTCCBGmgAwIBAgIKIMrVVAAAAAAATTANBgkqhkiG9w0BAQUFADBG
# MRIwEAYKCZImiZPyLGQBGRYCbmwxFjAUBgoJkiaJk/IsZAEZFgZuZWRjYXIxGDAW
# BgNVBAMTD05FRENBUi1WUzA1NC1DQTAeFw0xNTEyMDQxMzMwNDZaFw0xNjEyMDMx
# MzMwNDZaMGIxEjAQBgoJkiaJk/IsZAEZFgJubDEWMBQGCgmSJomT8ixkARkWBm5l
# ZGNhcjEiMCAGA1UECxMZRW50ZXJwcmlzZSBBZG1pbmlzdHJhdGlvbjEQMA4GA1UE
# AxMHTUo5MDYyNDCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAy6s27ycZWqct
# ddrqmqQraUr0iCZvwGZF5uQz82VB50Yc6BtW1H1P/vcF2p+1BYY6haidzExvwXCg
# W0GWSNLJTKYF290uJ6svPK849zkyU5NfbHqPYEY9oa8MCBpIh5NJ/9f511abTuLX
# BMFoZUvq5pj4W2s+kwUGcbXstvu9zVsCAwEAAaOCAtcwggLTMCUGCSsGAQQBgjcU
# AgQYHhYAQwBvAGQAZQBTAGkAZwBuAGkAbgBnMBMGA1UdJQQMMAoGCCsGAQUFBwMD
# MAsGA1UdDwQEAwIHgDAdBgNVHQ4EFgQU6mjlKV+1x8GQEQboF8vamA4j3SkwHwYD
# VR0jBBgwFoAUsU6fZORCtgnTXC2l1aRfWjVtWIQwggEABgNVHR8EgfgwgfUwgfKg
# ge+ggeyGgbJsZGFwOi8vL0NOPU5FRENBUi1WUzA1NC1DQSxDTj1WUzA1NCxDTj1D
# RFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29u
# ZmlndXJhdGlvbixEQz1uZWRjYXIsREM9bmw/Y2VydGlmaWNhdGVSZXZvY2F0aW9u
# TGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50hjVodHRw
# Oi8vdnMwNTQubmVkY2FyLm5sL0NlcnRFbnJvbGwvTkVEQ0FSLVZTMDU0LUNBLmNy
# bDCCARQGCCsGAQUFBwEBBIIBBjCCAQIwgawGCCsGAQUFBzAChoGfbGRhcDovLy9D
# Tj1ORURDQVItVlMwNTQtQ0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZp
# Y2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9bmVkY2FyLERDPW5s
# P2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0
# aG9yaXR5MFEGCCsGAQUFBzAChkVodHRwOi8vdnMwNTQubmVkY2FyLm5sL0NlcnRF
# bnJvbGwvVlMwNTQubmVkY2FyLm5sX05FRENBUi1WUzA1NC1DQS5jcnQwLAYDVR0R
# BCUwI6AhBgorBgEEAYI3FAIDoBMMEU1KOTA2MjRAbmVkY2FyLm5sMA0GCSqGSIb3
# DQEBBQUAA4IBAQA2UzothT/Xbu3fvZX/gNKBCP/xENekaFHB2WjNY+T7DJ9WldzJ
# Cv0d8dI2cTavjRSd0tWQWIi/AbHSpTGnZpECsn3adVCyK2Q/vXaA+h1rALLs2BTh
# qYKEAmOrUeC9CT9EXaDUF6Cn+A6wFxixDZ+4e9u7HdhBBvNQB14A1QmrDKxuHUTV
# sRjeaK7bAGndnnhAed/h/fR5e6eXU6Wm4D3rlggOjsrfEhBziUPRZEP3l8XsI6uu
# I87jGrJQLQ0qOpHolruBdHN3i/Rn7a4mhx76mcu3cuhvcee+BLIhYTgssI4n29mv
# n01t6q96Hz2KrJrrW3G/P+K6S2PIBw8NSu6dMYIBdDCCAXACAQEwVDBGMRIwEAYK
# CZImiZPyLGQBGRYCbmwxFjAUBgoJkiaJk/IsZAEZFgZuZWRjYXIxGDAWBgNVBAMT
# D05FRENBUi1WUzA1NC1DQQIKIMrVVAAAAAAATTAJBgUrDgMCGgUAoHgwGAYKKwYB
# BAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAc
# BgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUKFZ7
# kBqAKy/b5SLzMW361iBGD40wDQYJKoZIhvcNAQEBBQAEgYBrwj2Xvi/NAFNDXUxS
# zTamsBmJnmKCdoTm7b0JKd+xQ4zQMSmBus7+Gv0MNK+DO+a0u3Yn/zzx1boR8+va
# mW0SL7/dSzOIIves2IbnS6hWYotaxvAQgE5gFtOvAuPPAyo5PqTVzH25EfZiodho
# MPlraqMndU5a3hiEwI7xlpeMLQ==
# SIG # End signature block
